### ISSUE TITLE
WearableListenerService example in README

### ISSUE THREAD

**Issue by denley** [denley/courier#15]
Write an example of using Courier in a WearableListenerService, as this is a very common use and is not self-evident

**Comment by jkwiecien** [comment]
Please, please, I wasn't sure if it's possible with courier

**Comment by denley** [comment]
You basically just have to deserialize your object using the `Packager` class.

Example:
```java
MyDeliverableClass unpackedObject = Packager.unpack(dataItem, MyDeliverableClass.class);
```

You can provide a `byte[]` instead of a `DataItem` if you are unpacking a message.

It will first try to deserialize using the `@Deliverable` generated class for the target class, if it doesn't exist then it will try to use java's `Serializable` system. That way you can send primitives and Strings.

**Comment by denley** [comment]
The README has been updated regarding `WearableListenerService`. Let me know if anything about it is unclear, and I will update it further.

**Comment by jkwiecien** [comment]
outstanding. thanks a lot!
