### ISSUE TITLE
Method for checking whether wearable device is available

### ISSUE THREAD

**Issue by jkwiecien** [denley/courier#18]
I think we could use some method inside Courier class that would let us to check wheter device is avalible or not. According to the docs, if there is no wearable device connected, ```GoogleApiClient``` won't connect (```onConnectionFailed``` is fired). Mighbt a way to go.

**Comment by denley** [comment]
This is a good idea. It's definitely useful to check if the user has a wearable device or not.

To be clear on this issue: the API connection fails if the user doesn't have the `Android Wear` app installed (i.e. they don't own a watch). If the user has paired their watch but it is out of range of the phone it will still work properly, and the `@RemoteNodes` annotated fields/methods will receive an empty list.

**Comment by denley** [comment]
This has been added to the source. The method is `Courier.isWearableApiAvailable`. It will be included in the next release.

**Comment by denley** [comment]
Version 1.1.0 has just been released, which includes this method. Please check the readme for usage details.
