### ISSUE TITLE
Bump Google Play Services to 8.3

### ISSUE THREAD

**Issue by mitchross** [denley/courier#27]
Current version in Library is 8.1. Latest version is 8.3.

**Comment by denley** [comment]
As long as the API hasn't changed (the parts that Courier uses), you can force your app to use the latest version like so:

``` groovy
dependencies {
    compile 'me.denley.courier:courier:1.2.1
    compile 'com.google.android.gms:play-services-wearable:8.3.0'
}
```

Unless a new version breaks backwards compatibility, or there's a new feature we need to use for Courier, I don't see any reason to try to keep up with the dependency version.

**Comment by mitchross** [comment]
Yea I might have prematurely submitted this ticket. Thanks for replying anyway.
